#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#PBS -l vmem=8gb
#PBS -N App-Template-Matlab

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

# run the actual MatLab code

%This portion is Francos code 
set -e
set -x

export MAXMEM=19000000
time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main
%Stops here

./main.m
